export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const FETCH_PRODUCT = 'FETCH_PRODUCT';
export const FETCH_PRODUCT_LIST = 'FETCH_PRODUCT_LIST';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';

export const CREATE_INVOICE = 'CREATE_INVOICE';
export const EDIT_INVOICE = 'EDIT_INVOICE';
export const FETCH_INVOICE = 'FETCH_INVOICE';
export const FETCH_INVOICE_LIST = 'FETCH_INVOICE_LIST';
export const DELETE_INVOICE = 'DELETE_INVOICE';

export const FETCH_REPORT = 'FETCH_REPORT'